// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearLogs():Promise<void>;

export function GetLocalIPs():Promise<Array<string>>;

export function GetLogs():Promise<Array<main.LogEntry>>;

export function GetServerStatus():Promise<Record<string, any>>;

export function StartServer(arg1:string,arg2:number):Promise<void>;

export function StopServer():Promise<void>;
