// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function GetLocalIPs() {
  return window['go']['main']['App']['GetLocalIPs']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartServer(arg1, arg2) {
  return window['go']['main']['App']['StartServer'](arg1, arg2);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
